Workaround for VS2019 compiler bug that triggers deprecated error even if deprecated class is unused
VS throws compilation error simply from defining inline ctor of the deprecated class. Sample compilation error:
src\simdjson.h(4829,14): error C4996: 'simdjson::dom::parser::Iterator': Use the new DOM navigation API instead (see doc/usage.md) (compiling source file src\simdjson.cpp)